final: binsearch.o getch_ungetch.o getword.o main.o
	gcc -o final binsearch.o getch_ungetch.o getword.o main.o

binsearch.o: binsearch.c
	gcc -c binsearch.c
getch_ungetch.o: getch_ungetch.c
	gcc -c getch_ungetch.c
getword.o: getword.c
	gcc -c getword.c